import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';

/// Definición de temas claro y oscuro para la aplicación.
class AppTheme {
  // Tema claro
  static ThemeData light = FlexThemeData.light(
    colors: const FlexSchemeColor(
      primary: Color(0xff3d0079),
      primaryContainer: Color(0xfff5f5f5),
      secondary: Color(0xfffa9f16),
      secondaryContainer: Color(0xff9d38aa),
      tertiary: Color(0xff000000),
      tertiaryContainer: Color(0xffd5bbee),
      appBarColor: Color(0xff9d38aa),
      error: Color(0xffff4022),
      errorContainer: Color(0xffffdad6),
    ),
    subThemesData: const FlexSubThemesData(
      interactionEffects: true,
      tintedDisabledControls: true,
      useM2StyleDividerInM3: true,
      filledButtonRadius: 40.0,
      filledButtonSchemeColor: SchemeColor.secondary,
      switchSchemeColor: SchemeColor.secondary,
      inputDecoratorSchemeColor: SchemeColor.primaryContainer,
      inputDecoratorIsFilled: true,
      inputDecoratorBorderSchemeColor: SchemeColor.secondary,
      inputDecoratorBorderType: FlexInputBorderType.outline,
      inputDecoratorRadius: 7.0,
      inputDecoratorUnfocusedHasBorder: false,
      inputCursorSchemeColor: SchemeColor.tertiary,
      fabUseShape: true,
      fabRadius: 60.0,
      fabSchemeColor: SchemeColor.secondary,
      alignedDropdown: true,
      appBarBackgroundSchemeColor: SchemeColor.primary,
      bottomAppBarSchemeColor: SchemeColor.primaryContainer,
      tabBarItemSchemeColor: SchemeColor.primaryContainer,
      tabBarUnselectedItemSchemeColor: SchemeColor.outlineVariant,
      tabBarIndicatorSchemeColor: SchemeColor.primaryContainer,
      bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.onPrimary,
      bottomNavigationBarMutedUnselectedLabel: true,
      bottomNavigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
      bottomNavigationBarMutedUnselectedIcon: true,
      bottomNavigationBarBackgroundSchemeColor: SchemeColor.primary,
      navigationBarSelectedLabelSchemeColor: SchemeColor.onPrimary,
      navigationBarUnselectedLabelSchemeColor: SchemeColor.primaryContainer,
      navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
      navigationBarUnselectedIconSchemeColor: SchemeColor.primaryContainer,
      navigationBarIndicatorSchemeColor: SchemeColor.tertiaryContainer,
      navigationBarBackgroundSchemeColor: SchemeColor.primary,
      navigationRailUseIndicator: true,
      navigationRailBackgroundSchemeColor: SchemeColor.primaryContainer,
      navigationRailLabelType: NavigationRailLabelType.all,
    ),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    useMaterial3: true,
  );

  // Tema oscuro
  static ThemeData dark = FlexThemeData.dark(
    colors: const FlexSchemeColor(
      primary: Color(0xff9fc9ff),
      primaryContainer: Color(0xff00325b),
      secondary: Color(0xffffb59d),
      secondaryContainer: Color(0xff872100),
      tertiary: Color(0xff86d2e1),
      tertiaryContainer: Color(0xff004e59),
      appBarColor: Color(0xff9d38aa),
      error: Color(0xffffb4ab),
      errorContainer: Color(0xff93000a),
    ),
    subThemesData: const FlexSubThemesData(
      interactionEffects: true,
      tintedDisabledControls: true,
      blendOnColors: true,
      useM2StyleDividerInM3: true,
      switchSchemeColor: SchemeColor.secondary,
      inputDecoratorIsFilled: true,
      inputDecoratorBorderType: FlexInputBorderType.outline,
      inputDecoratorRadius: 7.0,
      inputDecoratorUnfocusedHasBorder: false,
      fabUseShape: true,
      fabAlwaysCircular: true,
      alignedDropdown: true,
      bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.onPrimary,
      bottomNavigationBarMutedUnselectedLabel: true,
      bottomNavigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
      bottomNavigationBarMutedUnselectedIcon: true,
      bottomNavigationBarBackgroundSchemeColor: SchemeColor.primary,
      navigationBarSelectedLabelSchemeColor: SchemeColor.onPrimary,
      navigationBarUnselectedLabelSchemeColor: SchemeColor.secondary,
      navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
      navigationBarUnselectedIconSchemeColor: SchemeColor.secondary,
      navigationBarIndicatorSchemeColor: SchemeColor.secondaryContainer,
      navigationBarBackgroundSchemeColor: SchemeColor.primary,
      navigationRailUseIndicator: true,
      navigationRailBackgroundSchemeColor: SchemeColor.primaryContainer,
      navigationRailLabelType: NavigationRailLabelType.all,
    ),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    useMaterial3: true,
  );
}
