name: pip_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^7.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.4
  firebase_database: ^11.1.4
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  image_picker: ^1.1.2
  backdrop: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/logo_pip.png
    - lib/assets/images/frogicon.jpg
    - lib/assets/images/paquete.png
    - lib/assets/images/doc.png
    - lib/assets/images/paquete.png
    - lib/assets/images/avatar.jpg
    - lib/assets/images/paquetelarge.png

  fonts:
    - family: Poppins-Bold # Nombre de la fuente
      fonts:
        - asset: lib/assets/fonts/Poppins-Bold.ttf
    
    - family: Poppins-Regular # Nombre de la fuente
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf

    - family: Poppins-Medium # Nombre de la fuente
      fonts:
        - asset: lib/assets/fonts/Poppins-Medium.ttf